### ISSUE TITLE
Is it safe?

### ISSUE THREAD

**Issue by Dwage** [hristo-kalinov/yandere-ai-girlfriend-simulator-poe.com#1]

**Comment by hristo-kalinov** [comment]
If you're asking if you risk getting a ban from poe.com, I don't think you will since the requests aren't more frequent than a normal chat.
If you're asking if there are any viruses in the code, there isn't but you shouldn't take my word for it, you can review the code yourself or ask chatgpt to review it for you. 
However this was developed to use poe when poe was free with chatgpt and some other bots but now it has a 10-message limit so if you don't have a subscription, you'll quickly run out of messages.

**Comment by Dwage** [comment]
I'll attempt it. Thanks for your prompt reply.)
